### ISSUE TITLE
Address is correct but the location on the map is forking wrong

### ISSUE THREAD

**Issue by i2000s** [akshaybajaj2280/wtfsigte#1]
Sorry, good app but a little off on the map. I don't know if it is just because I am in a small city called Albuquerque, NM, USA?

**Comment by akshaybajaj2280** [comment]
Hi Qi,

Are you using Albuquerque, NM, USA as the address or are you using a specific address?

Sincerely,
Akshay

**Comment by i2000s** [comment]
I am in the city, and the system detected my location correctly from the map... :)

**Comment by akshaybajaj2280** [comment]
Great! Glad it's sorted out. The location is determined by getting it from your browser. There could be cases where you location is invalid based on your ISP.

If you see more issues, definitely reach out to us, we're not developing any further, but would love to help.

Sincerely,
Akshay

**Comment by i2000s** [comment]
Sorry, I meant to say my location was detected correctly, but the restaurant location was not labeled correctly on the map.
